### ISSUE TITLE
The plugin does not work. Please update!

### ISSUE THREAD

**Issue by jagermeizter** [zorbeytorunoglu/thebestranks#16]
Please update your plugin to new versions, in its category it is the best there is. **If you create a premium version I will be the first to buy it**. But please don't abandon this project!

```
[00:28:22] [Server thread/ERROR]: [thebestranks] Material of passed is not set properly! We will replace it with ANVIL
[00:28:22] [Server thread/ERROR]: Error occurred while enabling thebestranks v2.0.3 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at kLib-0.0.8.jar/com.zorbeytorunoglu.kLib.version.Version.getVersion(Version.kt:13) ~[kLib-0.0.8.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.menu.MenuConfig.getItem(MenuConfig.kt:69) ~[thebestranks.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.menu.MenuConfig.<init>(MenuConfig.kt:33) ~[thebestranks.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.menu.MenuManager.<init>(MenuManager.kt:18) ~[thebestranks.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.TBR.onEnable(TBR.kt:38) ~[thebestranks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:28:22] [Server thread/INFO]: [thebestranks] Disabling thebestranks v2.0.3
```

**Comment by Erdnuss58** [comment]
Same! Don´t work in PaperMC 1.21

**Comment by zorbeytorunoglu** [comment]
I will update it guys, please be patient.
