### ISSUE TITLE
Error occurred while enabling thebestranks v2.0.3 (Is it up to date?) / 1.21

### ISSUE THREAD

**Issue by Erdnuss58** [zorbeytorunoglu/thebestranks#18]
`[14:03:23] [Server thread/ERROR]: Error occurred while enabling thebestranks v2.0.3 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:365) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:428) ~[?:?]
	at kLib-0.0.8.jar/com.zorbeytorunoglu.kLib.version.Version.getVersion(Version.kt:13) ~[kLib-0.0.8.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.menu.MenuConfig.getItem(MenuConfig.kt:69) ~[thebestranks.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.menu.MenuConfig.<init>(MenuConfig.kt:33) ~[thebestranks.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.menu.MenuManager.<init>(MenuManager.kt:18) ~[thebestranks.jar:?]
	at thebestranks.jar/com.zorbeytorunoglu.thebestranks.TBR.onEnable(TBR.kt:38) ~[thebestranks.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:638) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:587) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-90-dd11ef8]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[14:03:23] [Server thread/INFO]: [thebestranks] Disabling thebestranks v2.0.3`

**Comment by zorbeytorunoglu** [comment]
You are probably using it in 1.20.2 or above. I didn't add support for the new versions yet. I will update it so it won't require me to update kLib for every MC update.

**Comment by seetch** [comment]
> You are probably using it in 1.20.2 or above. I didn't add support for the new versions yet. I will update it so it won't require me to update kLib for every MC update.

How soon?
